//
//  languageNew.h
//  shinelink
//
//  Created by sky on 16/5/3.
//  Copyright © 2016年 sky. All rights reserved.
//

#ifndef languageNew_h
#define languageNew_h


#pragma mark - 登陆
#define  root_liji_tiyan       NSLocalizedString(@"1立即体验", nil)
#define  root_next_go        NSLocalizedString(@"2下一步", nil)
#define  root_finish        NSLocalizedString(@"3完成", nil)
#define  root_server_error        NSLocalizedString(@"4服务器错误", nil)
#define  root_paiZhao        NSLocalizedString(@"5拍照", nil)
#define  root_xiangkuang_xuanQu        NSLocalizedString(@"6从相册选取", nil)
#define  root_cancel        NSLocalizedString(@"7取消", nil)
#define  root_ALET        NSLocalizedString(@"8警告", nil)
#define  root_OK        NSLocalizedString(@"9确定", nil)
#define  root_del        NSLocalizedString(@"10删除", nil)
#define  root_saomiao_jieguo       NSLocalizedString(@"11扫描结果", nil)
#define  root_set       NSLocalizedString(@"12配置", nil)
#define  root_kongzhi_Alert      NSLocalizedString(@"13控制提示", nil)
#define  root_tianjia_wenti_Alert      NSLocalizedString(@"14添加问题提示", nil)
#define  root_kongzhi_mima      NSLocalizedString(@"15控制密码", nil)
#define  root_back      NSLocalizedString(@"16返回", nil)
#define  root_stop_config      NSLocalizedString(@"17停止配置", nil)
#define  root_zhuce_shibai      NSLocalizedString(@"18注册失败", nil)
#define  root_tuichu_zhanghu     NSLocalizedString(@"19是否退出当前账户", nil)

//登陆
#define  root_yongHuMing_mima_cuowu        NSLocalizedString(@"20用户名密码错误", nil)
#define  root_yongHuMing_mima_weikong        NSLocalizedString(@"21用户名密码为空", nil)
#define  root_Enter_your_username       NSLocalizedString(@"22Enter your username", @"Enter your username")
#define  root_Enter_your_pwd       NSLocalizedString(@"23Enter your pwd", @"Enter your pwd")
#define  root_forget_pwd       NSLocalizedString(@"24忘记密码?", nil)
#define  root_register       NSLocalizedString(@"25注册", nil)
#define  root_log_in      NSLocalizedString(@"26登录", nil)
#define  root_Alet_user_messge        NSLocalizedString(@"27请输入用户名", nil)
#define  root_Alet_user_pwd        NSLocalizedString(@"28请输入密码", nil)
#define  root_Alet_user        NSLocalizedString(@"29温馨提示", nil)
#define  root_old_pwd        NSLocalizedString(@"30原密码", nil)
#define  root_uid_weikong        NSLocalizedString(@"30UID为空", nil)
#define  root_liulanzhanghu        NSLocalizedString(@"30浏览账户", nil)

//注册,忘记密码
#define  root_forget_tips        NSLocalizedString(@"31成功后将发送新密码到账号绑定的邮箱", nil)
#define  root_zhengQueDe_yonghuMing       NSLocalizedString(@"32请输入正确的用户名", nil)
#define  root_youJian_shiBai       NSLocalizedString(@"33发送邮件失败", nil)
#define  HEM_zhucexinyonghu_tips  NSLocalizedString(@"34填写资料注册新用户",nil)
#define  root_tongyixieyi  NSLocalizedString(@"35同意本公司各项用户条款及隐私政策",nil)
#define  root_xuanze_yonghu_xieyi  NSLocalizedString(@"36选择用户协议", nil)
#define  root_shuru_zhengque_youxiang_geshi  NSLocalizedString(@"37请输入正确邮箱格式", nil)
#define  root_chaoChu_shuLiang       NSLocalizedString(@"38超出版本限制注册用户数量", nil)
#define  root_fuWuQi_cuoWu      NSLocalizedString(@"39服务器错误", nil)
#define  root_zhuCe_cuoWu       NSLocalizedString(@"40注册错误", nil)
#define  root_caijiqi_cuowu       NSLocalizedString(@"41采集器序列号或校验码错误", nil)
#define  root_yongHu_yi_shiYong       NSLocalizedString(@"42用户名已被使用", nil)
#define  root_dailishang_cuowu       NSLocalizedString(@"43代理商编码错误", nil)
#define  root_zhuCe_chengGong      NSLocalizedString(@"44注册成功", nil)
#define  root_xuliehao_yijing_cunzai      NSLocalizedString(@"45采集器序列号已经存在", nil)
#define  root_fuwuqi_cuowu_tishi    NSLocalizedString(@"46服务器错误提示", nil)
#define  root_fuwuqi_cuowu_tishi_2    NSLocalizedString(@"47服务器错误提示", nil)
#define  root_caijiqi_cuowu_tishi    NSLocalizedString(@"48采集器10位提示", nil)
#define  root_zhaoBuDao_yongHu       NSLocalizedString(@"49不能找到用户名", nil)
#define  root_542_dingwei_tishi NSLocalizedString(@"50打开定位开关", nil)
#define  root_543_dingwei_tishi_2 NSLocalizedString(@"51定位提示跳转", nil)
// 我的
#define  root_wode    NSLocalizedString(@"52我的", nil)
#define  root_WO_zhiliao_guanli        NSLocalizedString(@"53账号管理", nil)
#define  root_WO_xiaoxi_zhongxin      NSLocalizedString(@"54消息中心", nil)
#define  root_WO_guanyu        NSLocalizedString(@"55关于", nil)
#define  root_WO_xieyi        NSLocalizedString(@"56用户协议", nil)
#define  root_WO_zhuxiao_zhanhao     NSLocalizedString(@"57注销账号", nil)
#define  root_WO_zanweikaifang     NSLocalizedString(@"58暂未开放", nil)
#define  root_WO_xiugai_mima      NSLocalizedString(@"59修改密码", nil)
#define  root_WO_xiugai_shoujihao      NSLocalizedString(@"60修改手机号", nil)
#define  root_WO_xiugai_youxiang      NSLocalizedString(@"61修改邮箱", nil)
#define  root_budai_guojiahao      NSLocalizedString(@"62填入不带国家代码的手机号", nil)
#define  root_WO_shuru_youxiang     NSLocalizedString(@"63输入邮箱地址", nil)
#define  root_WO_shuru_dailishang    NSLocalizedString(@"64输入代理商编号", nil)
#define  root_xitong_cuoWu      NSLocalizedString(@"65系统错误", nil)
#define  root_yuan_mima_cuowu  NSLocalizedString(@"66原密码错误", nil)
#define  root_WO_yonghu_bucunzai     NSLocalizedString(@"67用户不存在", nil)
#define  root_zhanghu_meiyou_quanxian      NSLocalizedString(@"68你的账号没有操作权限", nil)
#define  root_CNJ_canshu_chenggong     NSLocalizedString(@"69参数设置成功", nil)
#define  root_yanzheng_zhuce_shoujihao  NSLocalizedString(@"70请验证注册时填写的手机号码", nil)
#define  root_yanzheng_yonghu_shoujihao  NSLocalizedString(@"71验证用户手机号码", nil)
#define  root_yanzheng_yonghu_youxiang  NSLocalizedString(@"72验证用户邮箱", nil)
#define  root_zhuce_tianxie_shoujihao  NSLocalizedString(@"73您注册时填写的手机号是", nil)
#define  root_shuru_duanxin_jiaoyanma    NSLocalizedString(@"74请输入短信验证码", nil)
//#define  root_shuru_duanxin_jiaoyanma    NSLocalizedString(@"75请输入短信验证码", nil)
#define  root_yanzhengma_cuowu    NSLocalizedString(@"76验证码错误", nil)
#define  root_fasong_yanzhengma    NSLocalizedString(@"77发送验证码", nil)
#define  root_guoji_quhao_cuowu  NSLocalizedString(@"78国际区号错误", nil)
#define  root_shouji_geshi_cuowu NSLocalizedString(@"79手机号格式错误", nil)
#define  root_fasongduanxin_yanzhengma_buchenggong NSLocalizedString(@"80发送短信验证码不成功", nil)
#define  root_gaishoujihao_meiyou_zhuce_yonghu NSLocalizedString(@"81该手机号没有注册用户", nil)
#define  root_shouji_yanzhengma_shixiao NSLocalizedString(@"82短信验证码请求已经失效", nil)
#define  root_qingshuru_zhengque_jiaoyanma     NSLocalizedString(@"83请输入正确的手机校验码", nil)

#define  root_WO_shifou_gengxin       NSLocalizedString(@"84是否更新", nil)
#define  root_WO_liji_gengxin       NSLocalizedString(@"85立即更新", nil)
#define  root_WO_zuixin_banben      NSLocalizedString(@"86最新版本为", nil)
#define  root_WO_zanbu       NSLocalizedString(@"87暂不", nil)
#define  root_WO_shi_zuixin_banben       NSLocalizedString(@"88您使用的是最新版本", nil)
#define  root_WO_pingguo_fuwuqi_shibai      NSLocalizedString(@"89请求苹果服务器失败", nil)
#define  root_dadianhua     NSLocalizedString(@"90拨打电话", nil)
#define  root_WO_banbenhao    NSLocalizedString(@"91当前版本:", nil)


#define  root_yongHuMing        NSLocalizedString(@"92用户名", nil)
#define  root_Mima        NSLocalizedString(@"93密码", nil)
#define  root_chongFu_miMa        NSLocalizedString(@"94重复密码", nil)
#define  root_chongFu_shuRu_miMa       NSLocalizedString(@"95重复输入密码", nil)
#define  root_dianzZiYouJian        NSLocalizedString(@"96电子邮箱", nil)
#define  root_DianHua        NSLocalizedString(@"97联系电话", nil)
#define  root_daiLiShangBianHao        NSLocalizedString(@"98代理商编号", nil)
#define  root_shuRu_daiLiShangBianHao        NSLocalizedString(@"99输入代理商编号", nil)
#define  root_xiangTong_miMa        NSLocalizedString(@"100请输入相同的密码", nil)
#define  root_daYu_san       NSLocalizedString(@"101用户名必须大于3位", nil)
#define  root_daYu_liu        NSLocalizedString(@"102密码必须大于6位", nil)
#define  root_Enter_email       NSLocalizedString(@"103输入邮箱", nil)
#define  root_Enter_phone_number       NSLocalizedString(@"104输入电话号码", nil)
#define  root_Networking      NSLocalizedString(@"105请求超时", nil)
#define  root_Yes       NSLocalizedString(@"106Yes", @"Yes")


// 充电桩
#define  HEM_tianjiashebei NSLocalizedString(@"107添加设备",nil)
#define  HEM_chongdianzhuang NSLocalizedString(@"108充电桩",nil)
#define  HEM_chongdian NSLocalizedString(@"109充电",nil)
#define  HEM_chongdianjilu NSLocalizedString(@"110充电记录",nil)
#define  HEM_zhuangtishezhi NSLocalizedString(@"111桩体设置",nil)
#define  HEM_xuanzezhongdianzhuang NSLocalizedString(@"112选择充电桩",nil)
#define  HEM_lianjie NSLocalizedString(@"113连接",nil)
#define  HEM_tingzhichongdian NSLocalizedString(@"114停止充电",nil)
#define  HEM_tianjianchongdianzhuang_tips NSLocalizedString(@"115输入充电桩序列号添加充电桩", nil)
#define  HEM_meiyoushebei NSLocalizedString(@"116您暂时还没有设备呢",nil)
#define  HEM_meiyou_jilu NSLocalizedString(@"117您暂时还没有充电记录呢",nil)
#define  HEM_meiyou_dingshi NSLocalizedString(@"118暂时还没有定时,请点击右上角进行添加",nil)

#define  HEM_A_qiang NSLocalizedString(@"119A枪",nil)
#define  HEM_B_qiang NSLocalizedString(@"120B枪",nil)
#define  HEM_C_qiang NSLocalizedString(@"121C枪",nil)
#define  HEM_jiaoliu NSLocalizedString(@"122交流",nil)
#define  HEM_zhiliu NSLocalizedString(@"123直流",nil)
#define  HEM_danqiang NSLocalizedString(@"124单枪",nil)
#define  HEM_shuangqiang NSLocalizedString(@"125双枪",nil)
#define  HEM_wu NSLocalizedString(@"126无",nil)

#define  HEM_Available NSLocalizedString(@"127空闲",nil)
#define  HEM_Charging NSLocalizedString(@"128充电中",nil)
#define  HEM_Preparing NSLocalizedString(@"129准备中",nil)
#define  HEM_Finishing NSLocalizedString(@"130充电结束",nil)
#define  HEM_Faulted NSLocalizedString(@"131故障",nil)
#define  HEM_Unavailable NSLocalizedString(@"132通讯异常",nil)
#define  HEM_SuspendedEV NSLocalizedString(@"133通讯异常",nil)
#define  HEM_expiry NSLocalizedString(@"134已经注销",nil)
#define  HEM_Accepted NSLocalizedString(@"135启用中",nil)
#define  HEM_work NSLocalizedString(@"136已经工作过",nil)

#define  HEM_setAmount_buweiling NSLocalizedString(@"137设置金额不能为0",nil)
#define  HEM_setEnergy_buweiling NSLocalizedString(@"138设置电量不能为0",nil)
#define  HEM_time_buweiling NSLocalizedString(@"139时长设置不能为空",nil)
#define  HEM_weishezhi_kaishishijian NSLocalizedString(@"140未设置开始时间",nil)
#define  HEM_wufachongdian NSLocalizedString(@"141空闲状态无法直接开始充电，请先连接车辆与充电桩",nil)

#define  root_MAX_300 NSLocalizedString(@"142切换", nil)
#define  HEM_tianjia NSLocalizedString(@"143添加",nil)
#define  root_shifou_shanchu_shebei    NSLocalizedString(@"144是否确定删除设备", nil)
#define  root_shifou_shanchu_shouquan    NSLocalizedString(@"145是否确定删除授权用户", nil)
#define  root_shanchu_chenggong      NSLocalizedString(@"146删除成功", nil)
#define  HEM_qingshuruchongdianzhuangID  NSLocalizedString(@"147请输入充电桩ID",nil)
#define  HEM_saomatianjia  NSLocalizedString(@"148扫码添加",nil)
#define  HEM_tianjiachongdianzhuang  NSLocalizedString(@"149添加充电桩",nil)
#define  root_ME_tianjia_chenggong     NSLocalizedString(@"150添加成功", nil)
#define  root_WO_buneng_weikong    NSLocalizedString(@"151不能为空", nil)
// 设置
#define  HEM_canshu_shezhi NSLocalizedString(@"152参数设置", nil)
#define  HEM_shouquanguanli NSLocalizedString(@"153授权管理", nil)
#define  HEM_jibencanshu NSLocalizedString(@"154基本参数",nil)
#define  HEM_zhongyaoshuju NSLocalizedString(@"155重要数据",nil)
#define  HEM_qitashuju NSLocalizedString(@"156其他数据",nil)
#define  HEM_shuru_genggai_shezhi NSLocalizedString(@"157输入更改的设置", nil)

#define  HEM_charge_id NSLocalizedString(@"158充电桩ID", nil)
#define  HEM_charge_miyao NSLocalizedString(@"159授权认证秘钥", nil)
#define  HEM_charge_jichucanshu NSLocalizedString(@"160基础参数",nil)
#define  HEM_charge_mingcheng NSLocalizedString(@"161电桩名称", nil)
#define  HEM_charge_guojia NSLocalizedString(@"162国家城市", nil)
#define  HEM_charge_zhandian NSLocalizedString(@"163站点", nil)
#define  HEM_charge_feilv NSLocalizedString(@"164充电费率", nil)
#define  HEM_charge_gonglv NSLocalizedString(@"165功率设置", nil)
#define  HEM_charge_moshi NSLocalizedString(@"166充电模式", nil)
#define  HEM_charge_gaojishezhi NSLocalizedString(@"167高级设置",nil)
#define  HEM_charge_ip NSLocalizedString(@"168充电桩IP", nil)
#define  HEM_charge_wangguang NSLocalizedString(@"169网关", nil)
#define  HEM_charge_yanma NSLocalizedString(@"170子网掩码", nil)
#define  HEM_charge_mac NSLocalizedString(@"171网络MAC地址", nil)
#define  HEM_charge_url NSLocalizedString(@"172服务器URL", nil)
#define  HEM_charge_dns NSLocalizedString(@"173DNS地址", nil)

#define  HEM_charge_model1 NSLocalizedString(@"174扫码/刷卡", nil)
#define  HEM_charge_model2 NSLocalizedString(@"175仅刷卡充电", nil)
#define  HEM_charge_model3 NSLocalizedString(@"176插枪充电", nil)
#define  HEM_tianjiashouquan  NSLocalizedString(@"177添加授权",nil)
#define  HEM_tianjiashouquanyonghu  NSLocalizedString(@"178输入用户名添加授权用户",nil)
#define  HEM_zhucexinyonghu  NSLocalizedString(@"179注册新用户",nil)
//#define HEM_zhucexinyonghu_tips  NSLocalizedString(@"180填写资料注册新用户",nil)
#define  HEM_qingshuruyonghumingchepaidianhuayouxiang  NSLocalizedString(@"181请输入用户名/车牌/电话/邮箱",nil)
#define  HEM_chongdian_tip1 NSLocalizedString(@"182现在正处于时段预约状态，如需立即开始充电，请关闭预约按键，并重新设置时长!",nil)
#define  HEM_delete_shouquan_tips NSLocalizedString(@"183不能删除桩主",nil)

// 蓝牙
#define  root_sousuo NSLocalizedString(@"184搜索", nil)
#define  root_lianjie_chenggong NSLocalizedString(@"185连接成功!", nil)
#define  root_charucheliang NSLocalizedString(@"186请将充电枪插入车辆!", nil)
#define  root_lanya NSLocalizedString(@"187蓝牙", nil)
#define  root_dakailanya NSLocalizedString(@"188连接充电桩需打开蓝牙", nil)
#define  root_wodeshebei NSLocalizedString(@"189我的设备", nil)
#define  root_kepeiduishebei NSLocalizedString(@"190可配对设备", nil)
#define  root_peijian NSLocalizedString(@"191配件", nil)

// 定时
#define  root_quereng NSLocalizedString(@"192确认", nil)
#define  root_geshi_cuowu NSLocalizedString(@"193输入格式不正确，请重新输入", nil)
#define  root_dingshi NSLocalizedString(@"194定时", nil)
#define  root_xinzeng NSLocalizedString(@"195新增", nil)
#define  root_yushefangan NSLocalizedString(@"196预设充电方案-时长：", nil)
#define  root_shezhidinghsi NSLocalizedString(@"197设置定时", nil)
#define  root_baocun NSLocalizedString(@"198保存", nil)
#define  root_kaiqi NSLocalizedString(@"199开启", nil)
#define  root_guanbi NSLocalizedString(@"200关闭", nil)
#define  root_weishezhi NSLocalizedString(@"201未设置", nil)
#define  root_meitian NSLocalizedString(@"202每天", nil)
#define  root_shanchu NSLocalizedString(@"203删除", nil)
#define  root_shi NSLocalizedString(@"204时", nil)
#define  root_fen NSLocalizedString(@"205分", nil)
#define  root_yushe NSLocalizedString(@"206预设", nil)
#define  root_shuru_amount NSLocalizedString(@"207请输入金额", nil)
#define  root_shuru_electricity NSLocalizedString(@"208请输入电量（kWh）", nil)
#define  root_time_set_Error NSLocalizedString(@"209时长设置有误", nil)
#define  root_time_set_Error2 NSLocalizedString(@"210开始时间不能小于当前时间", nil)

// 状态
#define  root_guoya NSLocalizedString(@"211过压", nil)

#define  root_charge_dianliang NSLocalizedString(@"212已充电量", nil)
#define  root_charge_feilv NSLocalizedString(@"213充电费率", nil)
#define  root_charge_shichang NSLocalizedString(@"214已充时长", nil)
#define  root_charge_jine NSLocalizedString(@"215消费金额", nil)
#define  root_charge_dianliu NSLocalizedString(@"216当前电流", nil)
#define  root_charge_dianya NSLocalizedString(@"217当前电压", nil)
#define  root_charge_yushe_jine NSLocalizedString(@"218预设金额", nil)
#define  root_charge_yushe_dianliang NSLocalizedString(@"219预设电量", nil)
#define  root_charge_yushe_shichang NSLocalizedString(@"220预设时长", nil)
#define  root_charge_yushe_fangan_jine NSLocalizedString(@"221预设方案 -金额", nil)
#define  root_charge_yushe_fangan_dianliang NSLocalizedString(@"222预设方案 -电量", nil)
#define  root_charge_yushe_fangan_shichang NSLocalizedString(@"223预设方案 -时长", nil)

#define  root_chongdianjieshu NSLocalizedString(@"224充电结束，请拔下充电枪，并将充电枪归位", nil)
#define  root_charge_state_available NSLocalizedString(@"225请连接充电枪到车辆", nil)
#define  root_charge_state_faulted NSLocalizedString(@"226电桩故障，请切换使用其他充电桩", nil)
#define  root_charge_state_unavailable NSLocalizedString(@"227桩体状态为不可用，请切换使用其他充电桩", nil)
//#define  root_yushe NSLocalizedString(@"228预设", nil)
#define  root_dangqian NSLocalizedString(@"229当前", nil)
#define  root_yushe_fangan NSLocalizedString(@"230预设充电方案", nil)
#define  root_yushe_tips NSLocalizedString(@"231(达到预设金额、电量、时长后停止充电)", nil)
#define  root_jine NSLocalizedString(@"232金额", nil)
#define  root_dianliang NSLocalizedString(@"233电量", nil)
#define  root_shichang NSLocalizedString(@"234时长", nil)
#define  root_yuyuechongdian NSLocalizedString(@"235预约充电", nil)
#define  root_kaishishijian NSLocalizedString(@"236开始时间", nil)
#define  root_yikaiqi NSLocalizedString(@"237已开启", nil)
#define  root_yiguanbi NSLocalizedString(@"238已关闭", nil)

#define  root_login_shibai NSLocalizedString(@"239登录失败", nil)
#define  root_yanzheng_demo NSLocalizedString(@"240浏览账户验证", nil)
#define  root_yanzheng_shibai NSLocalizedString(@"241验证失败", nil)
#define  root_yanzheng_chenggong NSLocalizedString(@"242验证成功", nil)

#define  root_shezhi_chenggong NSLocalizedString(@"243设置成功", nil)
#define  root_shezhi_shibai NSLocalizedString(@"244设置失败", nil)
#define  root_open_solar NSLocalizedString(@"245将充电功率限制为1KW", nil)
#define  root_close_solar NSLocalizedString(@"246将关闭充电功率限制", nil)

#endif /* languageNew_h */
